{
  "hash": "7700738801891dd1410eaa627aa6abff",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 3: Univariate distributions\"\nsubtitle: \"Data: NBA players\"\nengine: knitr\nfilters:\n  - ../../../../_extensions/coatless/webr/webr.lua\nformat:\n  revealjs:\n    theme: default\n    slide-number: true\n    transition: fade\n    toc: false\n    self-contained: false\n    smaller: true\n    scrollable: true\n    code-font-size: 1.15em\n    chalkboard:\n      buttons: true\n    code-tools:\n      source: true\n      toggle: false\neditor_options:\n  chunk_output_type: inline\n---\n\n\n\n## Prep work\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(Lock5Data)\nlibrary(tidyverse)\n?NBAPlayers2024\n#data(\"NBAPlayers2024\") # optional\n#data() # gives a list of available dataset\nNBAPlayers2024$pointsPerGame <-\n  NBAPlayers2024$Points/NBAPlayers2024$Games\n```\n:::\n\n\n# Univariate distribution: location, spread, and shape\n\n## Overview\n\n-   To describe a univariate distribution, we focus on three important properties: **location**, **spread**, and **shape**\n\n-   Tools: statistics, tables, and visualizations\n\n    -   A statistic is a numeric summary of data (e.g.: sample mean is a statistic; sample maximum is a statistic)\n\n-   Important statistics:\n\n    -   Mean, median, mode\n    -   Percentiles\n    -   Min, max\n    -   Range and Interquartile Range (IQR)\n    -   Standard deviation and variance\n\n## Location: mean, median, mode\n\n-   Location (also referred to as **central tendency**) is a measure of a typical/average value\n\n-   Example: what is the mean, median, and mode for this data?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsleep <- c(5,5,6,6,6,7,7,7,8,14)\n```\n:::\n\n\n-   For **numeric variables**, use mean and/or median\n    -   Example: typically, how many hours do students sleep?\n    -   Median is more **robust to outliers**\n    -   When mean and median are very different, it signals very **skewed** distribution and/or existence of outliers\n\n-   For **categorical variables** (i.e., factor), use mode\n    -   Example: based on **mtcars**, what kind of transmission type (0=automatic,1=manual) do cars typically have?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(mtcars$am)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 0  1 \n19 13 \n```\n\n\n:::\n:::\n\n\n-   In R (note, there is no built-in function for mode):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(sleep)\nmean(sleep)\nmedian(sleep)\ntable(sleep) # table () gives frequency for numeric variables\nsummary(as.factor(sleep)) # summary() gives frequency for factor variables\n# equivalent code with pipe operator\nsleep |> as.factor() |> summary()\n```\n:::\n\n\n-   Q: how can you convert the frequency to percentages?\n-   Q: how do you use R to automatically give you the mode?\n\n<details>\n<summary>Show code</summary>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n  sleep Freq Percent\n1     6    3     0.3\n2     7    3     0.3\n3     5    2     0.2\n4     8    1     0.1\n5    14    1     0.1\n```\n\n\n:::\n:::\n\n\n</details>\n\n\n## Percentiles\n\n-   The percentile (rank) of a value is the percentage **below** that value\n\n![](percentile_example.jpg){width=30%}\n\n-   The kth percentile of a variable is a value such that k percent are below that value\n\n    -   Example: [Growth charts for children](https://www.cdc.gov/growthcharts/html_charts/wtageinf.htm#females)\n    -   Example: [SAT scores](https://en.wikipedia.org/wiki/SAT)\n\n- Special percentiles: first, second and third quartiles (i.e., Q1, Q2, and Q3) correspond to the 25th, 50th, and 75th percentiles; Q2 is the median\n\n- Percentiles (especially Q1, Q2, and Q3) also provide a sense of the **location** of the distribution\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(NBAPlayers2024$pointsPerGame)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  4.273   9.769  13.375  14.442  19.085  34.692 \n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(NBAPlayers2024$pointsPerGame, c(0.95, 0.75, 0.05))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      95%       75%        5% \n26.032767 19.084507  6.121994 \n```\n\n\n:::\n:::\n\n\n## Spread: range and interquartile range (IQR)\n\n-   Spread can be measured by range and **interquartile range** (IQR)\n\n    -   range: min to max\n    -   IQR: Q1 to Q3 (i.e., range for the middle 50% of people)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(NBAPlayers2024$FG3Pct)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.     NAs \n 0.0000  0.3360  0.3640  0.3501  0.3910  0.4610       5 \n```\n\n\n:::\n\n```{.r .cell-code}\nrange(NBAPlayers2024$FG3Pct,na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.000 0.461\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(NBAPlayers2024$FGPct)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.3720  0.4400  0.4620  0.4777  0.4980  0.7470 \n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(NBAPlayers2024$FGPct, c(0.25, 0.75), na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  25%   75% \n0.440 0.498 \n```\n\n\n:::\n\n```{.r .cell-code}\nIQR(NBAPlayers2024$FGPct, na.rm = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.058\n```\n\n\n:::\n:::\n\n\n-   Are NBA players more consistent in their field goal shooting ability, or in 3-point field goal shooting ability?\n\n-   Range is very affected by outliers!\n\n\n## Boxplot\nBoxplot is based on **only five numbers**: min, Q1, Q2, Q3, max (also called the **five-number summary**)\n    \n\n<details>\n<summary>Show code</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nboxplot(NBAPlayers2024$FGPct,\n        main=paste('Field goal percentage'),\n        col='pink',\n        border='royalblue',\n        cex.main=0.8,range=0)\n\n# `text()` adds text to an *existing* plot at the specified coordinate\ntext(1.25,quantile(NBAPlayers2024$FGPct,na.rm = T),\n     labels=c('min','Q1','median','Q3','max'),\n     col='royalblue',\n     cex=0.7)\n```\n:::\n\n\n</details>\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lecture_3_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=50%}\n:::\n:::\n\n\n\n\n## Spread: standard deviation (SD) and variance\n\n-   SD is a measure of how spread out the data points are (\"average distance of each data point to the mean\")\n-   SD has the same unit as the data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nGPA <- c(3.2,3.3,3.4)\nsd(GPA)  #small SD, consistent GPA\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1\n```\n\n\n:::\n\n```{.r .cell-code}\nTEMP <- c(50,60,90,100)\nmean(TEMP); sd(TEMP) #large SD, lots of variation in temp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 75\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23.80476\n```\n\n\n:::\n:::\n\n\n-   Variance is the square of SD\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvar(GPA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01\n```\n\n\n:::\n:::\n\n\n## Shape: histogram and skewness\n\n-   For determining the direction of skewness, look for **tail values**; extreme tail values are referred to as **outliers**\n\n    - Tail values or extreme values are LARGE values: right skewed (positive skew); e.g., income, house price, etc.\n    - Tail values or extreme values are SMALL values: left skewed (negative skew); e.g., age at death, retirement age, etc.\n\n-   Histogram is a widely used **univariate** plot (in base R, use **hist()**)\n\n-   When describing shape, pay attention to: skewness, outliers, number of modes, and any other unusual pattern in the data\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lecture_3_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n## Exercise 1\n\nGive a thorough description of the variable **FGPct** (Field goal percent), using statistics and visualizations as needed. Mention properties of *location* and *spread*, and describe the *shape* of the distribution.\n\n<details>\n<summary>Show solution</summary>\n\nThe field-goal percentages based on NBA data from 2024 range from **0.372 to 0.747**. The mean is **0.478**, while the median is **0.462**, so a typical player has a field-goal percentage of about **46%**. The middle 50% of players have field-goal percentages from **0.440 to 0.498**, giving an interquartile range of **0.058**. The standard deviation is **0.062**.\n\nThe distribution is **right-skewed**: the mean is higher than the median, and the upper tail extends farther than the lower tail.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrange(NBAPlayers2024$FGPct, na.rm = TRUE)\nmean(NBAPlayers2024$FGPct, na.rm = TRUE)\nmedian(NBAPlayers2024$FGPct, na.rm = TRUE)\nquantile(NBAPlayers2024$FGPct, c(0.25, 0.75), na.rm = TRUE)\nIQR(NBAPlayers2024$FGPct, na.rm = TRUE)\nsd(NBAPlayers2024$FGPct, na.rm = TRUE)\nhist(NBAPlayers2024$FGPct, main = \"Field-goal percentage\", xlab = \"FGPct\", col = \"lightblue\", border = \"blue\")\n```\n:::\n\n\n</details>\n\n\n# Z-score\n\n## Z-score\n\n-   **Z-score** (also called standardized score) of a variable is calculated as `(value - mean) / sd`\n\n-   It's used to *standardize* a variable so that you can make sense of the value regardless of the scale or unit\n\n-   Example: Tom has an SAT of 1400. Jerry has an ACT of 28. Who has a better score? We know that:\n\n    -   SAT: mean=1100, sd=150\n    -   ACT: mean=25, sd=2\n\n-   Q: what's the z-score for Tom? for Jerry?\n-   Q: Interpretations of the z-scores?\n\n<details>\n<summary>Show solution</summary>\n\nTom's z-score is $(1400 - 1100) / 150 = 2$. Jerry's z-score is $(28 - 25) / 2 = 1.5$.\n\nTom's SAT score is **2 standard deviations above** the SAT mean, while Jerry's ACT score is **1.5 standard deviations above** the ACT mean. Relative to their respective tests, Tom has the higher score.\n\n</details>\n\nin R: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# by hand: a vector is created\na <- NBAPlayers2024$FGPct\nz1 <- (a - mean(a))/sd(a)\n\n# using scale function: a matrix is created\nz2 <- scale(NBAPlayers2024$FGPct)\n```\n:::\n\n\n\n## Exercise 2\n1. Calculate the z-scores of **FGPct** and **FG3Pct** and store the z-scores as separate variables in the data frame.\n\n2. Print the information for Stephen Curry and give an interpretation for the z-scores of **FGPct** and **FG3Pct**.  Relatively speaking, is he better at field goals or 3-point field goals? \n\n3. Find a player whose field goal percentage is above the average, but 3-point field goal percentage is below the average.\n\n4. Find a player who is very capable in both field goal and 3-point field goal.\n\n5. What is the mean and sd for the z-scores of **FGPct** and **FG3Pct**?\n\n<details>\n<summary>Show solution</summary>\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nNBAPlayers2024 <- NBAPlayers2024 %>%\n  mutate(FGPct.z = as.numeric(scale(FGPct)),\n         FG3Pct.z = as.numeric(scale(FG3Pct)))\n\nNBAPlayers2024 %>%\n  filter(Player == \"Stephen Curry\") %>%\n  select(Player, Team, FGPct, FG3Pct, FGPct.z, FG3Pct.z)\n\nNBAPlayers2024 %>%\n  filter(FGPct.z > 0, FG3Pct.z < 0) %>%\n  select(Player, Team, FGPct, FG3Pct, FGPct.z, FG3Pct.z,MinPerGame)%>%\n  arrange(desc(MinPerGame))\n\nNBAPlayers2024 %>%\n  filter(FGPct.z > 1, FG3Pct.z > 1) %>%\n  select(Player, Team, FGPct, FG3Pct, FGPct.z, FG3Pct.z)\n\nsummary(NBAPlayers2024$FGPct.z)\nsummary(NBAPlayers2024$FG3Pct.z)\n```\n:::\n\n\n1. Add the standardized variables with `scale()`, as shown in the code above.\n\n2. Stephen Curry's FGPct z-score is **-0.449**, while his FG3Pct z-score is **0.768**. His field-goal percentage is about 0.449 standard deviations BELOW the sample mean, while his 3-point percentage is 0.768 standard deviations ABOVE the sample mean. Relative to other players, he is stronger at 3-point field goals.\n\n3. **DeMar DeRozan** is one example: his FGPct is 0.038 SDs above the mean, while his FG3Pct is 0.226 SDs below the mean.\n\n4. **Jalen Williams** is one example of a player who is very capable in both areas: his FGPct z-score is 1.012 and his FG3Pct z-score is 1.020, so both are more than one standard deviation above their respective means.\n\n5. The mean of each z-score variable is approximately **0**, and the standard deviation is **1**; this is expected by how z-scores are calculated.\n\n</details>\n\n\n\n",
    "supporting": [
      "lecture_3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}