---
title: "Week 4"
format: html
---


## Overview

- Sep 22 (Tuesday): asynchronous lecture
- Sep 24 (Thursday): in-person lecture, **quiz 3**


## Tuesday, Sep 22 (asynchronous)

1. Study the posted slides of [Chapter 4](../../course_documents/all_lectures/chapter_4_slide.html){target="_blank"} on your own.  Note that the slides currently do not include the second half of Chapter 4 (Z-scores), which will be discussed after Exam 1.

2. Submit [Assignment 3](../../course_documents/assignment/assignment_3.qmd){target="_blank"} on Moodle before Thursday's class.

3. For additional practice, do problems 4.1, 4.4, and 4.5 from [Chapter 4 homework](../../course_documents/homework/chapter_4.html){target="_blank"}.

4. Note: there will be a quiz question based on the above material, as noted below.


## Thursday, Sep 24 (in-person)

**Quiz 3** (given at the beginning of the class) will have two main questions:

1. Very similar to the NYC apartment example in [Assignment 2](../../course_documents/assignment/assignment_2.qmd){target="_blank"}. Relevant content were discussed in [Chapter 3](../../course_documents/all_lectures/chapter_3_slide.html){target="_blank"}.

2. I will give you a linear transformation (e.g., ``new data = old data * 2 + 1``) and ask you to calculate new values of the mean, IQR, and skewness ratio after the transformation.

We discussed a few additional topics of Chapter 3, including modality and the effect of outliers.  These have been added to the end of [Chapter 3 slides](../../course_documents/all_lectures/chapter_3_slide.html){target="_blank"}.

To study for Exam 1, do the [practice Exam 1](../../course_documents/exam_reviews/practice_exam_1_blank.qmd){target="_blank"} and review the [solution](../../course_documents/exam_reviews/practice_exam_1_solution.qmd){target="_blank"}. I recommend downloading the pdf version of both files (slightly better formatted).

Reminder that you can find everything under [course documents](../../course_documents/index.qmd){target="_blank"}. Solutions to assignments are added. If anything is missing or a link is not working, please let me know.