---
title: "Week 3"
format: html
---

## Overview

- Sep 15 (Tuesday): in-person lecture, [**assignment 2**](../../course_documents/assignment/assignment_2.qmd){target="_blank"} (due before Thursday's class)
- Sep 17 (Thursday): in-person lecture, **quiz 2**

## Tuesday, Sep 15 (in-person)

We will begin [Chapter 3](../../course_documents/all_lectures/chapter_3_slide.html){target="_blank"}. Toward the end of the class, we will go over [**assignment 2**](../../course_documents/assignment/assignment_2.qmd){target="_blank"} and you need to submit your answers on Moodle before Thursday's class.

[Link to fullscreen](../../course_documents/all_lectures/chapter_3_slide.html){target="_blank"}

<iframe src="../../course_documents/all_lectures/chapter_3_slide.html" width="100%" height="650px" style="border:none;"></iframe>


## Thursday, Sep 17 (in-person)

We will finish [Chapter 3](../../course_documents/all_lectures/chapter_3_slide.html){target="_blank"}. We will also start the discussion of [Chapter 4](../../course_documents/all_lectures/chapter_4_slide.html){target="_blank"}.

[Link to Chapter 4 slides](../../course_documents/all_lectures/chapter_4_slide.html){target="_blank"}

**Quiz 2** (given at the beginning of the class) will be based on content from [Chapter 2](../../course_documents/all_lectures/chapter_2_slide.html){target="_blank"} and [Homework 2](../../course_documents/homework/chapter_2.qmd){target="_blank"}.  In addition, it involves Jamovi and you are expected to understand the basics of using Jamovi, as outlined in [assignment 1](../../course_documents/assignment/assignment_1.qmd){target="_blank"}.

Reminder: since we finished Chapter 3, you should do [homework questions for Chapter 3](../../course_documents/homework/chapter_3.qmd){target="_blank"}.