---
title: "Course documents"
---

You can find all course documents here as a reference page. Please refer to the [weekly modules](../weeks/index.qmd) for specifics on what you need to do each week.

## Lecture slides

- [Lecture 1: Introduction and discrete random variables](all_lectures/Lecture_1.html)
- [Lecture 2: Common discrete distributions](all_lectures/Lecture_2.html)
- [Lecture 3: Implementing simulations](all_lectures/Lecture_3.html)
- [Lecture 4: Common continuous distributions](all_lectures/Lecture_4.html)
- [Lecture 5: Rejection and SIR sampling](all_lectures/Lecture_5.html)
- [Lecture 6: Model based inference](all_lectures/Lecture_6.html)
- [Lecture 7: Bootstrapping](all_lectures/Lecture_7.html)
- [Lecture 8: Empirical p-values](all_lectures/Lecture_8.html)
- [Lecture 9: Introduction to Bayesian inference and MCMC](all_lectures/Lecture_9.html)

## Homework

- [Homework 1](homework/homework_1.qmd)
- [Homework 2](homework/homework_2.qmd)
- [Homework 3](homework/homework_3.qmd)


## Assignments

- [Assignment 1 (Group discussion based on Homework 1)](assignment/assignment_1.qmd)
- [Assignment 2 (Group discussion based on Homework 2)](assignment/assignment_2.qmd)

## Exam reviews

- [Exam 1 Review](exam_reviews/exam_1_review.qmd)
