---
title: "Course documents"
---

You can find all course documents here as a reference page.  Please refer to the [weekly modules](../weeks/index.qmd) for specifics on what you need to do each week.

## Lecture slides

- [Chapter 1: Introduction](all_lectures/chapter_1_slide.html)
- [Chapter 2: Examining Univariate Distributions](all_lectures/chapter_2_slide.html)
- [Chapter 3: Locations, Spread, and Skewness](all_lectures/chapter_3_slide.html)
- [Chapter 4: Transformations and Z-scores](all_lectures/chapter_4_slide.html)
`

## Homework

Homework exercise questions are adopted from the textbook *Statistics Using IBM SPSS (3rd edition)*, by S. Weinberg and S. Abramowitz, Cambridge University Press ISBN 9781107461222.

Solutions are provided in the same document.

If a dataset is missing, or if you find a typo/error, please let me know.

- [Homework Chapter 1](homework/chapter_1.qmd)
- [Homework Chapter 2](homework/chapter_2.qmd)
- [Homework Chapter 3](homework/chapter_3.qmd)
- [Homework Chapter 4](homework/chapter_4.qmd)


## Assignment

- [Assignment 1: Jamovi Introduction](assignment/assignment_1.qmd)
- [Assignment 2: NYC Apartments](assignment/assignment_2.qmd)
- [Assignment 3: Song length transformation](assignment/assignment_3.qmd)


## Practice exams

- [Practice Exam 1](exam_reviews/practice_exam_1_blank.qmd)
- [Practice Exam 1 solution](exam_reviews/practice_exam_1_solution.qmd)