---
title: "Dataset"
---

## SPSS data

### Combined Class data

These data were collected by STAT117 students at Drew University.

- [Combined Class Books.sav](../../../dataset/Combined%20Class%20Books.sav){download="Combined Class Books.sav"}
- [Combined Class Charities.sav](../../../dataset/Combined%20Class%20Charities.sav){download="Combined Class Charities.sav"}
- [Combined Class Movies Fall 2019.sav](../../../dataset/Combined%20Class%20Movies%20Fall%202019.sav){download="Combined Class Movies Fall 2019.sav"}
- [Combined Class Movies.sav](../../../dataset/Combined%20Class%20Movies.sav){download="Combined Class Movies.sav"}
- [Combined Class NJ homes FA18.sav](../../../dataset/Combined%20Class%20NJ%20homes%20FA18.sav){download="Combined Class NJ homes FA18.sav"}
- [Combined Class NYC Apartments.sav](../../../dataset/Combined%20Class%20NYC%20Apartments.sav){download="Combined Class NYC Apartments.sav"}
- [Combined Class Recipes.sav](../../../dataset/Combined%20Class%20Recipes.sav){download="Combined Class Recipes.sav"}
- [Combined Class Shoes.sav](../../../dataset/Combined%20Class%20Shoes.sav){download="Combined Class Shoes.sav"}
- [Combined Class Song Data.sav](../../../dataset/Combined%20Class%20Song%20Data.sav){download="Combined Class Song Data.sav"}
- [Combined Class eBayToys.sav](../../../dataset/Combined%20Class%20eBayToys.sav){download="Combined Class eBayToys.sav"}

### Textbook data

These data are from *Statistics Using IBM SPSS (3rd edition)*, by S. Weinberg and S. Abramowitz, Cambridge University Press ISBN 9781107461222. A description of these datasets can be found in the [Appendix A data set descriptions](../../../dataset/Appendix_A_Data_Set_Descriptions_final.pdf){target="_blank"}.

- [NELS.sav](../../../dataset/NELS.sav){download="NELS.sav"}
- [Blood.sav](../../../dataset/Blood.sav){download="Blood.sav"}
- [Currency.sav](../../../dataset/Currency.sav){download="Currency.sav"}
- [Framingham.sav](../../../dataset/Framingham.sav){download="Framingham.sav"}
- [Hamburg.sav](../../../dataset/Hamburg.sav){download="Hamburg.sav"}
- [Icecream.sav](../../../dataset/Icecream.sav){download="Icecream.sav"}
- [Impeach.sav](../../../dataset/Impeach.sav){download="Impeach.sav"}
- [Learndis.sav](../../../dataset/Learndis.sav){download="Learndis.sav"}
- [Marijuana.sav](../../../dataset/Marijuana.sav){download="Marijuana.sav"}
- [States.sav](../../../dataset/States.sav){download="States.sav"}
- [Temp.sav](../../../dataset/Temp.sav){download="Temp.sav"}
- [Wages.sav](../../../dataset/Wages.sav){download="Wages.sav"}
- [basketball.sav](../../../dataset/basketball.sav){download="basketball.sav"}
- [mandex.sav](../../../dataset/mandex.sav){download="mandex.sav"}
- [stepping.sav](../../../dataset/stepping.sav){download="stepping.sav"}

### Other SPSS data

- [General Social Survey 2016.sav](../../../dataset/General%20Social%20Survey%202016.sav){download="General Social Survey 2016.sav"}
- [Music.sav](../../../dataset/Music.sav){download="Music.sav"}
- [Student Survey.sav](../../../dataset/Student%20Survey.sav){download="Student Survey.sav"}
- [Young People Survey partial.sav](../../../dataset/Young%20People%20Survey%20partial.sav){download="Young People Survey partial.sav"}
- [Young People Survey.sav](../../../dataset/Young%20People%20Survey.sav){download="Young People Survey.sav"}