<!DOCTYPE html>
<html lang="en"><head>
<script src="chapter_4_slide_files/libs/clipboard/clipboard.min.js"></script>
<script src="chapter_4_slide_files/libs/quarto-html/tabby.min.js"></script>
<script src="chapter_4_slide_files/libs/quarto-html/popper.min.js"></script>
<script src="chapter_4_slide_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="chapter_4_slide_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="chapter_4_slide_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="chapter_4_slide_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <title>Chapter 4: Transformations and Z-scores</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="chapter_4_slide_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="chapter_4_slide_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="chapter_4_slide_files/libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link href="chapter_4_slide_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="chapter_4_slide_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="chapter_4_slide_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="chapter_4_slide_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="chapter_4_slide_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="chapter_4_slide_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="center">
  <h1 class="title">Chapter 4: Transformations and Z-scores</h1>
  <p class="subtitle">STAT117: Introduction to Statistics</p>
  <div style="position: absolute; bottom: 0; font-size: 0.5em; color: #888;">
  Some narrative text in <em>Lecture notes and summary</em> are drafted by AI. They are fully proofread and verified by the instructor. Also, R code for generating output are optional.
  </div>
</section>
<section id="why-transform-a-variable" class="slide level2">
<h2>Why transform a variable?</h2>
<p>There are several common reasons to transform data:</p>
<ul>
<li>convert from one unit to another, such as inches to centimeters or Celsius to Fahrenheit;</li>
<li>reverse the direction of a variable coding, such as changing (<code>1 = Agree</code> and <code>5 = Disagree</code>) to (<code>1 = Disagree</code> and <code>5 = Agree</code>);</li>
<li><em>standardize</em> data so scores measured on different scales or unit can be compared.</li>
</ul>
<p>The central question is: <strong>How does a transformation affect the distribution of a variable?</strong></p>
<p>Specifically, we want to consider what happens to:</p>
<ul>
<li><strong>location:</strong> mode, median, and mean</li>
<li><strong>spread:</strong> range, IQR, and standard deviation</li>
<li><strong>shape:</strong> skewness ratio</li>
</ul>
</section>
<section id="linear-transformations" class="slide level2">
<h2>Linear transformations</h2>
<p>A <strong>linear transformation</strong> has the form</p>
<p><span class="math display">\[
    \text{new data} = K*(\text{old data}) + C,
\]</span></p>
<p>where <code>K</code> and <code>C</code> are constants.</p>
<ul>
<li><code>K</code> represents a <em>scale factor</em></li>
<li><code>C</code> represents a <em>location shift</em></li>
</ul>
<p>Examples:</p>
<ul>
<li><p><code>new = 2(old) + 3</code> (scale everything up by 2; shift everything to the right by 3)</p></li>
<li><p><code>new = -1.5(old) - 10</code> (scale factor = -1.5; shift everything to the left by 10)</p></li>
<li><p><code>new = (old)/10</code> (scale factor = 1/10, no location shift)</p></li>
</ul>
</section>
<section id="effect-on-location" class="slide level2">
<h2>Effect on location</h2>
<p>Location statistics mimic the transformation:</p>
<p><span class="math display">\[
    \text{new statistic} = K*(\text{old statistic}) + C
\]</span></p>
<p>This rule applies to the <strong>mode</strong>, <strong>median</strong>, and <strong>mean</strong>.</p>
<p>For example, if the original mean is 20 and <code>new = 3*(old) + 4</code>, then</p>
<p><span class="math display">\[
    \text{new mean} = 3*(20) + 4 = 64.
\]</span></p>
<p>If the original median is 15 and <code>new = -2*(old) + 5</code>, then <span class="math display">\[
    \text{new median} = -2*(15) + 5 = -25.
\]</span></p>
</section>
<section id="effect-on-spread" class="slide level2">
<h2>Effect on spread</h2>
<p>Spread statistics are affected by the <strong>magnitude</strong> of <code>K</code>, but not by <code>C</code>:</p>
<p><span class="math display">\[
    \text{new spread} = |K|*(\text{old spread})
\]</span></p>
<p>This rule applies to the <strong>range</strong>, <strong>IQR</strong>, and <strong>standard deviation</strong>.</p>
<p>Note 1: These statistics are always positive, hence the absolute value in the formula.</p>
<blockquote>
<p>Intution: the spread of a distribution is a measure of distance, which is always positive: the distance from my house to Drew is 2 miles, and the distance from Drew to my house is also 2 miles. You would never say that the distance from my house to Drew is “-2 miles.”</p>
</blockquote>
<p>Note 2: The <strong>location shift</strong> <code>C</code> does not affect the spread of the distribution.</p>
<blockquote>
<p>Intuition: if you move the entire distribution to the right or left, the distance between the values does not change (neither does the shape, so C also does not affect the skewness ratio).</p>
</blockquote>
<p>For example, if the original data has a min of 0 and max of 4, then the range is 4. If <code>new = 2*(old) + 3</code>, then the new min is 3 and the new max is 11, so the new range is 8, or simply <code>|2|(4) = 8</code>. If <code>new = -3*(old) + 4</code>, then the new min is 4 and the new max is -8, so the new range is 12, or simply <code>|-3|(4) = 12</code>.</p>
<p>If the original standard deviation is 5 and <code>new = -3*(old) + 4</code>, then</p>
<p><span class="math display">\[
    \text{new SD} = |-3|(5) = 15.
\]</span></p>
</section>
<section id="effect-on-skewness" class="slide level2">
<h2>Effect on skewness</h2>
<p>The skewness ratio is affected only by the <strong>sign</strong> of <code>K</code>:</p>
<p><span class="math display">\[
    \text{new skewness ratio} =
\begin{cases}
    \text{old skewness ratio}, &amp; K &gt; 0 \\
    -\text{old skewness ratio}, &amp; K &lt; 0
\end{cases}
\]</span></p>
<p>In other words, multiplying by a positive number does not change the skewness ratio. Multiplying by a negative number reverses the sign of the skewness ratio.</p>
<blockquote>
<p>Intuition: imagine a distribution with a range of 0 to 10. If you multiply by 2, the range becomes 0 to 20, but the shape is the same. If you multiply by -2, the range becomes -20 to 0. The old minimum becomes the new maximum, and the shape is reversed: left skewed becomes right skewed, and right skewed becomes left skewed.</p>
</blockquote>
</section>
<section id="example-1-celsius-to-fahrenheit" class="slide level2">
<h2>Example 1: Celsius to Fahrenheit</h2>
<p>The conversion from Celsius to Fahrenheit is</p>
<p><span class="math display">\[
F = \frac{9}{5}C + 32.
\]</span></p>
<p>Suppose a set of Celsius temperatures has mean 14.6, standard deviation 5, IQR 7, range 20, and skewness ratio 0.8. Calculate the corresponding Fahrenheit statistics.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Celsius</th>
<th style="text-align: left;">Fahrenheit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: right;">14.6</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Standard deviation</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">IQR</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Range</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Skewness ratio</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<p>In addition, as a review, what does the skewness ratio tell us about the shape of the distribution?</p>
<details>
<summary>
Show solution
</summary>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Celsius</th>
<th style="text-align: right;">Fahrenheit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: right;">14.6</td>
<td style="text-align: right;">58.28</td>
</tr>
<tr class="even">
<td style="text-align: left;">Standard deviation</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IQR</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">12.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Range</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">36</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Skewness ratio</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.8</td>
</tr>
</tbody>
</table>
The Fahrenheit distribution has the same shape, but a different center and spread because <code>K = 9/5</code> is positive. The skewness ratio of 0.8 indicates that the distribution is roughly symmetric.
</details>
</section>
<section id="example-2-reversing-a-scale" class="slide level2">
<h2>Example 2: reversing a scale</h2>
<p><span class="math display">\[
    \text{new data} = -2*(\text{old data}) + 5.
\]</span></p>
<p>If the old mean is 3, the old standard deviation is 1.5, the old IQR is 2, and the old skewness ratio is 2.4, calculate the new statistics.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Old data</th>
<th style="text-align: right;">New data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Standard deviation</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">IQR</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Skewness ratio</td>
<td style="text-align: right;">2.4</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p>In addition, what does the skewness ratio tell us about the shape of the distribution?</p>
<details>
<summary>
Show solution
</summary>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Old data</th>
<th style="text-align: right;">New data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;"><code>-2(3) + 5 = -1</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Standard deviation</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;"><code>|-2|(1.5) = 3</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">IQR</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"><code>|-2|(2) = 4</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Skewness ratio</td>
<td style="text-align: right;">2.4</td>
<td style="text-align: right;"><code>-2.4</code></td>
</tr>
</tbody>
</table>
The negative value of <code>K</code> reverses the direction of the distribution. The skewness ratio of the old distribution, 2.4, indicates that the distribution is severely right-skewed. The new skewness ratio of -2.4 indicates that the distribution is severely left-skewed. The shape is reversed because we multiplied by a negative number.
</details>
</section>
<section id="example-3-transform-ses-in-nels" class="slide level2">
<h2>Example 3: transform SES in NELS</h2>
<p>Use the NELS variable <code>ses</code>, Socio-Economic Status, and define</p>
<p><span class="math display">\[
    \text{SESNEW} = -2*(\text{SES}) + 5.
\]</span></p>
<p>As practice, open the NELS dataset in Jamovi and verify the listed summary statistics for <code>ses</code>. Then, use the transformation rules to calculate the summary statistics for <code>SESNEW</code>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;"><code>ses</code></th>
<th style="text-align: right;"><code>SESNEW = -2*(ses) + 5</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: right;">18.434</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Median</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standard deviation</td>
<td style="text-align: right;">6.924</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">IQR</td>
<td style="text-align: right;">10.25</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Range</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Skewness ratio</td>
<td style="text-align: right;">-1.03</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<details>
<summary>
Show solution
</summary>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;"><code>ses</code></th>
<th style="text-align: right;"><code>SESNEW = -2*(ses) + 5</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: right;">18.434</td>
<td style="text-align: right;">-31.868</td>
</tr>
<tr class="even">
<td style="text-align: left;">Median</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">-33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standard deviation</td>
<td style="text-align: right;">6.924</td>
<td style="text-align: right;">13.849</td>
</tr>
<tr class="even">
<td style="text-align: left;">IQR</td>
<td style="text-align: right;">10.25</td>
<td style="text-align: right;">20.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Range</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">70</td>
</tr>
<tr class="even">
<td style="text-align: left;">Skewness ratio</td>
<td style="text-align: right;">-1.03</td>
<td style="text-align: right;">1.03</td>
</tr>
</tbody>
</table>
</details>
</section>
<section id="example-4-reverse-a-likert-scale" class="slide level2 scrollable">
<h2>Example 4: reverse a Likert scale</h2>
<p>Suppose a Likert scale variable measures agreement with the statement <strong>“I like statistics”</strong>:</p>
<ul>
<li><code>1 = Strongly Agree</code></li>
<li><code>2 = Agree</code></li>
<li><code>3 = Neither agree nor disagree</code></li>
<li><code>4 = Disagree</code></li>
<li><code>5 = Strongly Disagree</code></li>
</ul>
<p>Its summary statistics are mean = 2.56, median = 2, IQR = 2, and skewness ratio = 2.11.</p>
<p>We want to recode the variable so that high scores correspond to more interest in statistics:</p>
<ul>
<li><code>1 = Strongly Disagree</code></li>
<li><code>2 = Disagree</code></li>
<li><code>3 = Neither agree nor disagree</code></li>
<li><code>4 = Agree</code></li>
<li><code>5 = Strongly Agree</code></li>
</ul>
<ol type="a">
<li><p>Write down the linear transformation to do so.</p></li>
<li><p>What are the mean, median, IQR, and skewness ratio of the transformed variable?</p></li>
</ol>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Original scale</th>
<th style="text-align: right;">Reversed scale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: right;">2.56</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Median</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">IQR</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Skewness ratio</td>
<td style="text-align: right;">2.11</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<details>
<summary>
Show solution
</summary>
<p>The linear transformation is</p>
<p><span class="math display">\[
    \text{new} = -1*(\text{old}) + 6.
\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Original scale</th>
<th style="text-align: right;">Reversed scale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: right;">2.56</td>
<td style="text-align: right;"><code>-1(2.56) + 6 = 3.44</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Median</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"><code>-1(2) + 6 = 4</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">IQR</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"><code>|-1|(2) = 2</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Skewness ratio</td>
<td style="text-align: right;">2.11</td>
<td style="text-align: right;"><code>-2.11</code></td>
</tr>
</tbody>
</table>
</details>
</section>
<section>
<section id="z-scores" class="title-slide slide level1 center">
<h1>Z-scores</h1>

</section>
<section id="why-calculate-z-scores" class="slide level2">
<h2>Why calculate z-scores?</h2>
<p>We want to <strong>standardize</strong> data so that we can compare scores regardless of their original unit or scale.</p>
<ul>
<li>Motivating example 1: Tom has an SAT score of 1400. Jerry has an ACT score of 28. Who has the better score relative to the other students who took the same test?</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Test</th>
<th style="text-align: right;">Raw score</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SAT</td>
<td style="text-align: right;">1400</td>
<td style="text-align: right;">1100</td>
<td style="text-align: right;">150</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACT</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
<details>
<summary>
Show solution
</summary>
Tom’s SAT z-score is <code>(1400 - 1100) / 150 = 2</code>. Jerry’s ACT z-score is <code>(28 - 25) / 2 = 1.5</code>. Tom scored higher relative to test-takers on his exam.
</details>
<p><br></p>
<ul>
<li>Motivating example 2: In the NELS dataset, the <code>SES</code> score of student ID 1 is 23. How do we make sense of this value? What about for student with ID 2?</li>
</ul>
<details>
<summary>
Show solution
</summary>
In NELS, student 1 has <code>SES = 23</code> and student 2 has <code>SES = 20</code>. Using the SES mean of 18.434 and standard deviation of 6.924, their z-scores are approximately <code>(23 - 18.434) / 6.924 = 0.66</code> and <code>(20 - 18.434) / 6.924 = 0.23</code>. Both are above the mean; student 1 is farther above it.
</details>
</section>
<section id="z-score-definition" class="slide level2">
<h2>Z-score: definition</h2>
<p>The formula for calculating a z-score is:</p>
<p><span class="math display">\[
\textit{z-score} = \frac{\textit{raw score} - \textit{mean}}{\textit{sd}}
\]</span></p>
<p>To convert a z-score back to the raw score: <span class="math display">\[
\textit{raw score} = \textit{z-score} \times \textit{sd} + \textit{mean}
\]</span></p>
</section>
<section class="slide level2">

<p>For example, the z-score for SES is calculated as</p>
<p><span class="math display">\[
z_{SES} = \frac{\text{SES} - 18.4}{6.92}
\]</span></p>
<ul>
<li>Why is this a linear transformation?</li>
</ul>
<p><br></p>
<ul>
<li>What is the mean of <span class="math inline">\(z_{SES}\)</span>?</li>
</ul>
<p><br></p>
<ul>
<li>What is the standard deviation of <span class="math inline">\(z_{SES}\)</span>?</li>
</ul>
<p><br></p>
<ul>
<li>What is the skewness ratio of <span class="math inline">\(z_{SES}\)</span>?</li>
</ul>
<p><br></p>
<details>
<summary>
Show solution
</summary>
<p>The z-score is a linear transformation because it can be written as <code>z_SES = (1/6.92)*SES - 18.4/6.92</code>, which has the form <code>K*(old data) + C</code>.</p>
<ul>
<li>The mean is 0.</li>
<li>The standard deviation is 1.</li>
<li>The skewness ratio is unchanged because the scale factor <code>1/6.92</code> is positive; for SES, it is approximately -1.03.</li>
</ul>
</details>
<p>Interpretation examples:</p>
<blockquote>
<p>If z-score is 0.7: The raw score is 0.7 standard deviations ABOVE the mean.</p>
</blockquote>
<blockquote>
<p>If z-score is -1.2: The raw score is 1.2 standard deviations BELOW the mean.</p>
</blockquote>
</section>
<section id="example-achievement-scores-nels" class="slide level2 scrollable">
<h2>Example: achievement scores (NELS)</h2>
<ol type="1">
<li>A tenth-grade student scored 53 on both the math achievement test (<code>achmat10</code>) and the reading achievement test (<code>achrdg10</code>). The mean and standard deviation values for each variable can be found using <code>Jamovi - Analyses - Exploration - Descriptives</code>.</li>
</ol>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Test</th>
<th style="text-align: right;">Student score</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Math (<code>achmat10</code>)</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">7.84</td>
</tr>
<tr class="even">
<td style="text-align: left;">Reading (<code>achrdg10</code>)</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">56.1</td>
<td style="text-align: right;">8.30</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>What is the z-score for her math achievement?</li>
</ol>
<p><br></p>
<ol start="2" type="a">
<li>What is the z-score for her reading achievement?</li>
</ol>
<p><br></p>
<ol start="3" type="a">
<li>Based on z-scores, on which test did she do better relative to her peers?</li>
</ol>
<p><br></p>
<ol start="4" type="a">
<li>Based on cumulative percentage, on which test did she do better relative to her peers?</li>
</ol>
<p><br></p>
<ol start="2" type="1">
<li>Another 10th grade student from the NELS dataset has a z-score of 2.1 for the math achievement test (<code>achmat10</code>). Is this a good score? What is the student’s raw score?</li>
</ol>
<p><br></p>
<details>
<summary>
Show solution
</summary>
<ol type="a">
<li><p>Math: <code>(53 - 57) / 7.84 = -0.51</code>.</p></li>
<li><p>Reading: <code>(53 - 56.1) / 8.30 = -0.37</code>.</p></li>
<li><p>She did better relative to peers on reading: its z-score is higher (less below the mean).</p></li>
<li><p>The empirical cumulative percentages in NELS are 28.6% for math and 32.0% for reading, so reading is also higher by cumulative percentage.</p></li>
</ol>
For the second student, a z-score of 2.1 is unusually high. The raw score is <code>2.1*7.84 + 57 = 73.464</code>, or about 73.5.
</details>
</section>
<section id="example-nba" class="slide level2 scrollable">
<h2>Example: NBA</h2>
<p>The following information are given in the <code>NBAPlayers2024</code> data from <a href="https://www.lock5stat.com/datapage4e.html">Statistics: Unlocking the Power of Data</a>.</p>
<p><strong>LeBron James</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Raw score</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">z-score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rebounds per game</td>
<td style="text-align: right;">7.30</td>
<td style="text-align: right;">5.11</td>
<td style="text-align: right;">2.41</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Field-goal percentage</td>
<td style="text-align: right;">0.540</td>
<td style="text-align: right;">0.478</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Three-point percentage</td>
<td style="text-align: right;">0.410</td>
<td style="text-align: right;">0.350</td>
<td style="text-align: right;">0.075</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p><strong>Stephen Curry</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">Raw score</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">z-score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rebounds per game</td>
<td style="text-align: right;">4.46</td>
<td style="text-align: right;">5.11</td>
<td style="text-align: right;">2.41</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Field-goal percentage</td>
<td style="text-align: right;">0.450</td>
<td style="text-align: right;">0.478</td>
<td style="text-align: right;">0.062</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Three-point percentage</td>
<td style="text-align: right;">0.408</td>
<td style="text-align: right;">0.350</td>
<td style="text-align: right;">0.075</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Calculate each z-score.</li>
</ol>
<p><br></p>
<ol start="2" type="a">
<li>Which skill set is LeBron James better at relative to his peers? What about Stephen Curry?</li>
</ol>
<p><br></p>
<ol start="3" type="a">
<li>If you only consider the three skill sets listed above, who is a better player, overall, Lebron James or Stephen Curry?</li>
</ol>
<details>
<summary>
Show solution
</summary>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Player</th>
<th style="text-align: right;">Rebounds z-score</th>
<th style="text-align: right;">Field-goal z-score</th>
<th style="text-align: right;">Three-point z-score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LeBron James</td>
<td style="text-align: right;"><code>(7.30 - 5.11) / 2.41 = 0.91</code></td>
<td style="text-align: right;"><code>(0.540 - 0.478) / 0.062 = 1.00</code></td>
<td style="text-align: right;"><code>(0.410 - 0.350) / 0.075 = 0.80</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Stephen Curry</td>
<td style="text-align: right;"><code>(4.46 - 5.11) / 2.41 = -0.27</code></td>
<td style="text-align: right;"><code>(0.450 - 0.478) / 0.062 = -0.45</code></td>
<td style="text-align: right;"><code>(0.408 - 0.350) / 0.075 = 0.77</code></td>
</tr>
</tbody>
</table>
LeBron is above average in all three skills; Curry is above average in three-point shooting and below average in the other two. If the three skills are weighted equally, LeBron’s average z-score is about 0.90, compared with about 0.02 for Curry, so LeBron is better overall on this limited comparison.
</details>
</section>
<section id="z-scores-and-outliers" class="slide level2">
<h2>Z-scores and outliers</h2>
<p>What kind of z-score values would be considered <strong>unusual</strong>?</p>
<p>Exercise: pick a numeric variable from the NELS dataset and calculate the raw scores for the following z-scores.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">z-score</th>
<th style="text-align: center;">raw-score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">-0.5</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">1.5</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">-4.5</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">12.5</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<details>
<summary>
Show solution
</summary>
<p>For an example, use <code>SES</code>, with mean 18.4 and standard deviation 6.92. Convert each z-score with <code>raw score = z-score*6.92 + 18.4</code>:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">z-score</th>
<th style="text-align: right;">Example SES raw score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: right;">18.40</td>
</tr>
<tr class="even">
<td style="text-align: center;">-0.5</td>
<td style="text-align: right;">14.94</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1.5</td>
<td style="text-align: right;">28.78</td>
</tr>
<tr class="even">
<td style="text-align: center;">-4.5</td>
<td style="text-align: right;">-12.74</td>
</tr>
<tr class="odd">
<td style="text-align: center;">12.5</td>
<td style="text-align: right;">104.90</td>
</tr>
</tbody>
</table>
The last two are mathematical extrapolations and would be far outside the plausible SES range; the exercise can use any numeric variable, so answers vary with the selected variable.
</details>
<ul>
<li><p>For many numerical variables, it is <em>unlikely</em> to be more than 2 SD’s away from the mean (<a href="https://en.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule">4.5% chance if the distribution is normal</a> – more on this later).</p></li>
<li><p>As a result, if a z-score is greater than 2 or less than -2, we could consider the corresponding raw score as an outlier.</p></li>
</ul>
</section>
<section id="summary" class="slide level2">
<h2>Summary</h2>
<ul>
<li><a href="https://en.wikipedia.org/wiki/Standard_score">Z-score</a> (also called “standard score”) is defined via the linear transformation formula.</li>
</ul>
<p><br></p>
<ul>
<li><p>The distribution of z-scores for any variable would have a mean of 0 and a standard deviation of 1 (by definition).</p></li>
<li><p>Because the definition of a z-score involves the mean and standard deviation, it only really makes sense to talk about z-scores with numeric variables.</p></li>
<li><p>We can use z-scores to determine <strong>outliers</strong>. For instance, we can call a raw score an outlier if its z-score is greater than 2 or less than -2.</p></li>
<li><p>We can standardize a variable using:</p>
<pre><code>  - z-score

  - cumulative percentage (i.e., percentile rank)</code></pre></li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="chapter_4_slide_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="chapter_4_slide_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="chapter_4_slide_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="chapter_4_slide_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="chapter_4_slide_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="chapter_4_slide_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="chapter_4_slide_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="chapter_4_slide_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="chapter_4_slide_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="chapter_4_slide_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="chapter_4_slide_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>