---
title: "Schedule and reminders"
---

## Week 1

- Sep 1: Course introduction, [syllabus](syllabus.qmd), [R](https://cran.r-project.org/) and [RStudio](https://docs.posit.co/ide/user/#rstudio-ide-oss-downloads) setup, and getting started with [Lecture 1](lectures/lecture_1/lectures_1.html).  If not already done in class, please install R and RStudio on your computer before our next class.  

- Sep 3: **Quiz 1** on the basics of R.  If you understand everything we have covered on Sep 1, you should be fine.


## Week 2
- Sep 8: We are not meeting in person today (as I'll be travelling). Instead, please finish [Lecture 1](lectures/lecture_1/lectures_1.html) on your own and do [Homework 1](homework/homework_1.qmd) for extra practice.  Recall that homework is not collected in this class.

- Sep 10: Quiz 2, based on content from [Lecture 1](lectures/lecture_1/lectures_1.html) and [Homework 1](homework/homework_1.qmd).







## Overall schedule (from [syllabus](syllabus.qmd)):
| Week | Date | Note |
|---|---|---|
| 1 | Sep 1 | |
| | Sep 3 | Quiz 1 |
| 2 | Sep 8 | No (in-person) class: self-learning content will be assigned |
| | Sep 10 | Quiz 2 |
| | | (Sep 14 is the last day to drop without W) |
| 3 | Sep 15 | |
| | Sep 17 | Quiz 3 |
| 4 | Sep 22 | |
| | Sep 24 | Quiz 4 |
| 5 | Sep 29 | |
| | Oct 1 | **Midterm Exam 1** |
| 6 | Oct 6 | |
| | Oct 8 | Quiz 5 |
| 7 | Oct 13 | No class - Fall Break |
| | Oct 15 | Project workshop #1 |
| 8 | Oct 20 | |
| | Oct 22 | Quiz 6 |
| 9 | Oct 27 | |
| | Oct 29 | Quiz 7 |
| 10 | Nov 3 | |
| | Nov 5 | **Midterm Exam 2** |
| 11 | Nov 10 | Project workshop #2 |
| | Nov 12 | |
| 12 | Nov 17 | (Last day to drop with W) |
| | Nov 19 | Quiz 8 |
| 13 | Nov 24 | Project workshop #3 |
| | Nov 26 | No class — Thanksgiving |
| 14 | Dec 1 | Presentation: group A |
| | Dec 3 | Presentation: group B |
| 15 | Dec 8 | Presentation: group C |
| | Dec 10 | Quiz 9 |

: {tbl-colwidths="[10,15,75]"}

Optional second chance final exam: **Dec 17 (Thu) 4 - 7 pm**

Final project report: **due Dec 18 (Fri) at noon**