---
title: "Syllabus"
---

Download the pdf version [here](FA2026_STAT117_005_syllabus.pdf){download="STAT117_SYLLABUS.pdf"}.

**STAT 117 - Introduction to Statistics (Section 005)**  
**Fall 2026**

Instructor: Prof. Yi Lu  Email: ylu1@drew.edu  Office: HS 314  
Lectures: TR 10:25 - 11:40, HS 244 (hybrid)  
Office Hours: R 12-2 or by appointment (in-person HS314 or via Google Meet; link on course webpage)


**Description.** Introduces statistics needed for data analysis and to understand statistical content in the media. Uses a widely-used software application for statistics. May include graphical and tabular presentation of data, measures of central tendency, dispersion, and shape, linear transformations of data, correlation, regression, basic probability, and the normal probability model, sampling, hypothesis testing t-tests, and one-way analysis of variance.


**Course webpage.** Course content will be posted on <https://lu08.github.io/teaching/STAT117/>. Assignments, quizzes, and grades will be posted on Moodle. You should check both the course webpage and Moodle frequently. You should also check your email frequently for important announcements.

**Hybrid format.** This section is taught in a hybrid modality and will include asynchronous course content. To keep things clear and organized, everything you need to know is organized as **weekly modules** (<https://lu08.github.io/teaching/STAT117/weeks/>).  This is also where you should check to see whether we will be meeting in person.  When we are not meeting in person, I will be in my office (HS314) for the duration of the scheduled lecture time and you are welcome to stop by (the classroom is also available for you to use).  **Importantly, all quizzes and exams must be taken in person, absolutely no exceptions.**

**Learning Outcomes.**  By the end of the course, students will be able to:

1. Select, create, and interpret appropriate graphical displays, descriptive statistics, and inferential statistics. Apply the concepts of robustness and model validation;
2. Analyze real data within authentic applications;
3. Assess the quality of a statistical argument;
4. Use a professional statistical software package;
5. Interpret results in language that is both statistically correct and understandable by someone who has not taken a course in statistics;
6. Apply statistical reasoning in broad areas of application including the social, biological, and physical sciences.


**Laptop Computer and Statistical Software.**  We will be using the free, open-source statistical software **Jamovi** (<https://jamovi.org/download.html>).  Jamovi is a simple point-and-click interface, built directly on top of **R**, one of the most widely used programming languages in statistics and data science. Don't worry about programming or technical details as these are not the focus of our class. When needed, detailed instructions and sample code will be given to you. Toward the end of the semester, we will explain and demonstrate some basics of R.


**Optional Text.** *Statistics Using IBM SPSS (3rd edition)*, by S. Weinberg and S. Abramowitz, Cambridge University Press ISBN 9781107461222. The text includes indexed chapters and exercises and a URL where you may access online solutions. There is a copy of the text available on reserve at the library if you prefer to use that. You do not need to bring your copy of the text to class because the required exercises are available online.  You do not need to purchase the text unless reading the content is helpful.  Some students find it helpful to use it as a reference because all of the content is indexed.  Most students just need the exercises and solutions, which are available for free online.

**To clarify**: <u>we are NOT using SPSS for this section.</u> The textbook is consistent with other sections of STAT117 and is not an issue because (1) statistical concepts, as outlined in the textbook, do not depend on the software used; and (2) Jamovi's interface is intentionally made similar to SPSS.  Supplementary reading, assignments, and material will be posted on the course webpage.



**Dataset.**  The dataset used for the course will be shared on the course webpage.  You need to download a dataset first and open it in Jamovi.  To make sure that you are using the correct dataset for quizzes and exams, I strongly recommend that you never save a modified dataset.  You could also re-download a dataset before a quiz or an exam.  I emphasize that it is your responsibility to use the correct dataset, and "my dataset is different" is not a legitimate reason for an incorrect answer under any circumstances.

**Electronic devices.**  You are expected to bring a working laptop to each lecture.  *If your computer has issues, know that your course performance will be heavily affected* as everything (homework, quizzes, exams) requires the use of Jamovi.  It is your responsibility to avoid this situation and solve any computer issues in time.

You are allowed to use an iPad (or similar devices) for class-related activities (such as taking notes).  *You are prohibited from using cell phones, headphones, and earbuds during all lectures.*  You are also prohibited from using electronic devices for unrelated activities, such as browsing the internet, messaging, gaming, working on assignments from a different course, etc.

**Attendance.**  You are expected to attend every class unless you have a legitimate excuse, such as illness, family emergency or participation in a college sponsored event.  Attendance is mandatory for successful completion of the course.  Regardless of reason, it is your responsibility to make up course material covered during absences.  Note that poor attendance without a valid reason is not an excuse to misuse office hours.

Class attendance and participation are integral to the academic experience at Drew University.  Along with the course attendance policy, which may outline how attendance will affect a student's grade, students should also be aware of their rights and responsibilities regarding absences for legitimate reasons, as described in the Absence Policy: Student Rights and Responsibilities, which is located in the Academic Policy section of Drew's course catalog under Attendance (<https://drew-undergraduate-catalog.coursedog.com/pages/h3iCIMkMOg5fz3KTJDgC>).  Legitimate planned absences may include religious holidays, NCAA-sanctioned competition, academic conference or some Drew-sanctioned events.  Students need to inform the faculty member of planned absences in the first week of the semester.  For unforeseen extended health issues please see the academic accommodations statement.

**Late work and Missed Assignments.** <u>There are no make-ups in this class, even for excused absences</u>.  Instead, your two lowest quiz grades and two lowest assignment grades are dropped.  If you have excused absences for the course, these are part of your drops.  *All absences and late submissions will result in a grade of zero on assignments and quizzes*, but as long as these absences are not excessive, these zero grades will be dropped.  If you have an excused absence for an exam, I will use your performance on the final exam in place of the missing exam grade.  If you know in advance that you will miss a quiz or exam, you may be able to take it early by making appropriate arrangements with me.


**Homework.**  Textbook problems and solutions can be found on the course webpage.  Homework is not collected in this class, but it is *required* for you to do these problems.  It is possible that materials from the homework appear on quizzes and exams, even if they do not appear in the lecture.

**Components of Your Grades:**

- **10%** Assignments (in-class and take-home, lowest 2 dropped)

  During the semester, we'll do a few in-class activities and at-home assignments that will count toward your grade.   Since these assignments are not announced ahead of time, your regular attendance and consistent interaction with asynchronous content are important.  You are also expected to actively participate during in-person lectures and group activities.

- **17%** Quizzes (lowest 2 dropped)

  To make sure you are not falling behind, there will be a quiz *at the beginning* of (almost) every Thursday.  The quiz will be on Moodle.  There is no make-up quiz and you will not be allowed extra time if you join the class late, *even if you have excused reasons*, but your two lowest grades will be dropped.   Note that the last quiz on ANOVA (see below) does not fall in this category and therefore cannot be one of the two drops.

- **3%** ANOVA grade

  You can get this grade by (1) taking the last quiz ("ANOVA quiz") OR (2) taking the ANOVA portion on the final exam.   If you take both, this grade will be the higher of the two.

- **45%** Three in-class exams (15% each)

  There will be three in-class exams.  You are encouraged to make a reference sheet for each exam: An 8.5 by 11 inch (or A4) piece of paper with whatever you want on it, double sided. In addition to being useful during the exam, creating this sheet is a good way to study and prepare for the exam. You can use these same sheets for the final exam.

- **25%** (Optional) final exam

  There is an optional final exam during finals week. I will provide you with your course grade before the final, and you can choose to accept that grade and skip the final.

  The final exam is cumulative. You are encouraged to bring four reference sheets to the final exam: Four 8.5 by 11 inch (or A4) pieces of paper with whatever you want on it, double sided.

  You can choose to do only the ANOVA portion of the final exam for the ANOVA grade.  In this case, you are essentially still skipping the final and will not get a final exam grade.

**A Second Chance.** If you take the final exam, you will earn two sets of grades.  The exam consists of four parts. Parts 1 through 3 roughly correspond to the same material as exams 1 through 3, respectively, while part 4 covers new material learned after the third exam.

- The first final exam grade considers the total number of points earned on the exam, and is your final exam score counting for 25% of your final grade.
- The other set of final exam grades is a score for each of parts 1 through 3 of the final exam.  For each of these parts, if the final exam grade is *higher* than what you scored on the corresponding midterm exam, we will *raise* your score on that midterm exam. The new score on the midterm will be the average of the original score and the score on that part of the final.  If your final exam performance is not higher, the original midterm score is left unchanged.

**Final Exam Policy.** If extenuating circumstances occur, students may submit a Final Exam Reschedule request for review by the Associate Provost. Students may not negotiate a make-up date directly with the course instructor. Students may request to reschedule an exam only under the following circumstances:

- Two final exams scheduled at the same time;
- Three final exams scheduled in one calendar day; one of the exams will be rescheduled at the convenience of the instructor and the student;
- Serious illness, or personal emergency; the student is required to present documentation to validate.

The final exam schedule is visible on the Registrar's website by the beginning of each semester (<https://drew.edu/academic/office-of-the-registrar/registration/final-exam-schedule/>).  Students are expected to schedule travel plans to occur AFTER their final exams.


**Grade Cutoffs:** We will use the following scale in determining your course grade from your course average.  The course grades are not curved.   A = 94 to 100; A- = 90 to 93; B+ = 87 to 89; B = 84 to 86; B- = 80 to 83; C+ = 77 to 79; C = 74 to 76; C- = 70 to 73; D+ = 67 to 69; D = 64 to 66; D- = 60 to 63; F = 0 to 59.


**Academic Accommodations.**  Your experience in this class is important to me.
If you have already established accommodations with the Office of Accessibility Resources (OAR), please provide me with a copy of your accommodation letter at your earliest convenience so we can discuss your needs in this course.

If you have not yet established services through the Office of Accessibility Resources (OAR), but have a temporary health condition or permanent disability that requires accommodations (conditions include but not limited to; mental health, attention-related, learning, vision, hearing, physical or health impacts), you are encouraged to contact OAR.  OAR offers resources and coordinates reasonable accommodations for students with disabilities and/or temporary health conditions.

Although a disclosure may take place at any time during the semester, students are encouraged to do so early in the semester, because, in general, accommodations are not implemented retroactively.  Office of Accessibility Resources contact information:  
Interim Director: Stefanie Attia &nbsp;&nbsp; Location: Brothers College, Room 119B  
Phone: 973-408-3962 &nbsp;&nbsp; Email: oar@drew.edu


**Academic Integrity Policy.**  All students are required to uphold the highest academic standards.  Any case of academic dishonesty will be dealt with according to the guidelines and procedures outlined in Drew University's "Standards of Academic Integrity: Guidelines and Procedures," which is located in the academic policies section of the catalog (<https://drew-undergraduate-catalog.coursedog.com/academicpolicies#academic-integrity-policy>).

**Supporting Student Success, Center for Academic Excellence.** All Drew students can access subject tutoring, writing support and academic coaching free of charge in the Center for Academic Excellence (CAE, <https://drew.edu/academic/student-resources/center-for-academic-excellence/>), located in the library. Seeking help through learning support resources in the CAE can help you achieve your academic goals. To access the appointment schedule, please visit <https://drew.mywconline.com/> and follow the instructions on the landing page; if a tutor is not available, please submit the Tutor Request form. For any other questions, email cae@drew.edu.



**Artificial Intelligence.**  I encourage you to explore Artificial Intelligence (AI) resources for learning purposes.   When using AI, you must (1) fully document and cite all material (including any code, graph, formula, table, mathematical equation, etc.) that was not generated by you, (2) check information generated by AI and take full responsibility for its accuracy, and (3) be able to identify where and how you used any AI tools and how they contributed to your work.  You are not allowed to use AI for any quizzes or exams.  Use of any AI tools without permission is unacceptable and will be reported as an academic integrity violation. If you have any doubts about what is acceptable please discuss them with the professor.

**Schedule.** Important dates are summarized below.  Any change will be communicated in class and via email.  Course content is subject to change depending on the pace of the class.  Detailed weekly modules can be found at <https://lu08.github.io/teaching/STAT117/weeks/>.  Remember that the quiz and exam dates are always in-person.  Modality for the other dates will be communicated in the weekly modules.  Reach out if you are not sure.

| Week | Date | Content | Note |
|:----:|------|---------|------|
| 1 | Sep 1 | Ch1: Introduction | |
|  | Sep 3 | Ch2: Univariate distribution | **Quiz 1** |
| 2 | Sep 8 | Intro to Jamovi | |
|  | Sep 10 |  | **Quiz 2** |
|  |  | (Sep 14 is the last day to drop without W) | |
| 3 | Sep 15 | Ch3: Location, Spread, and Skewness | |
|  | Sep 17 |  | **Quiz 3** |
| 4 | Sep 22 | Ch4: Transformation | |
|  | Sep 24 |  | **Quiz 4** |
| 5 | Sep 29 |  | **EXAM 1** |
|  | Oct 1 | Ch5: Bivariate Relationships | |
| 6 | Oct 6 |  | |
|  | Oct 8 |  | **Quiz 5** |
| 7 | Oct 13 |  | No class - Fall Break |
|  | Oct 15 |  | |
| 8 | Oct 20 |  | |
|  | Oct 22 |  | **Quiz 6** |
| 9 | Oct 27 | Ch6: Simple Linear Regression | |
|  | Oct 29 |  | **Quiz 7** |
| 10 | Nov 3 |  | **EXAM 2** |
|  | Nov 5 | Ch7: Basic Probability | |
| 11 | Nov 10 | Ch8: Normal Distribution | |
|  | Nov 12 | Ch9: Central Limit Theorem | **Quiz 8** |
| 12 | Nov 17 | Ch11 Part 1: One sample t test | |
|  | Nov 19 |  | **Quiz 9** |
| 13 | Nov 24 | Ch11 Part 2: Paired samples t test | |
|  | Nov 26 |  | No class — Thanksgiving |
| 14 | Dec 1 | Ch11 Part 3: Independent samples t test | **Quiz 10** |
|  | Dec 3 |  | **EXAM 3** |
| 15 | Dec 8 |  | |
|  | Dec 10 |  | **ANOVA quiz** |

(Optional) final exam: **Dec 15 (Tue) 12:30 - 3:30 pm**


