---
title: "STAT120 - Statistical Computing in R / DATA505 - Statistics Using R"
---

Welcome to the course site of STAT120 - Statistical Computing in R / DATA505 - Statistics Using R. Use the sidebar to navigate within this course.

**Description.** (STAT120) Provides students with an introduction to computing in the popular statistical programming language R. Topics may include: data structures, reading and storing data, data transformation and manipulation, accessing and using packages, conditionals, loops, functions, graphics and data visualization, and introductory statistical methods for data analysis. No previous programming experience is required.

(DATA505) Covers how to use real-world data and draw intelligent conclusions on it using univariate and bivariate descriptive statistics such as centrality, spread, and correlation. Students have the opportunity to learn how to use the R language in the R-studio environment to obtain representative samples from large datasets and use the information in such samples to draw inferences on the larger datasets they were taken from. Course topics include graphical and tabular presentation of data, measures of central tendency, spread and shape, linear transformations of data, correlation, regression, probability, the normal probability model, sampling, t-tests, and one-way analysis of variance.