---
title: "Lecture 1: Introduction"
subtitle: "Data: Breakfast cereals"
engine: knitr
filters:
  - ../../../../_extensions/coatless/webr/webr.lua
format:
  revealjs:
    theme: default
    slide-number: true
    transition: fade
    toc: false
    self-contained: false
    smaller: true
    scrollable: true
    chalkboard:
      buttons: true
    code-tools:
      source: true
      toggle: false
editor_options: 
  chunk_output_type: inline
---

# Getting started

## R and RStudio

- RStudio is an **Integrated Development Environment** (IDE) for R.  You need to download BOTH [R](https://cran.r-project.org/) and [RStudio](https://docs.posit.co/ide/user/#rstudio-ide-oss-downloads) for RStudio to work.

- While you can write R code without RStudio or another IDE, the interface is not as nice.

- As a temporary alternative: you can use [Posit Cloud](https://posit.cloud/) to run RStudio online without installing anything on your computer.


## R script

Start a new R script: File - New File - R Script. Do NOT choose “new project.”

Default layout of RStudio:

- Upper left (R Script): this is a text file (.R format) that contains all the code you write
- Lower left (Console): this is where your code is run (i.e., R will provide feedback and result here)
- Upper right: contains information for the current R session
- Lower right: contains information for files and packages; plots and help pages will also show up here

A few reminders:

- When you open an R script (i.e., a .R document), make sure it's opened in RStudio (to change the default: Right click - Get Info - Open with RStudio - Change All)
- Have a habit of saving R script often when you are coding
- When exit RStudio, you should **only save the R script** ("save workspace image?" - Don't Save)
- You can easily upload files to Posit Cloud, or download files from Posit Cloud


## R code
Run code directly in the console:

- you just need to **hit enter** in the console
- Fast and easy
- However: nothing is saved; can only run one line at a time

(Recommended) Write code in R scripts:

- Can save the R scripts to run or modify your code in the future 
- Can write many lines of code and run portions of it as needed

To run code from an R script:

- if you have **any highlighted code**
   + hit **command + enter** (mac) or **ctrl + enter** (windows)
   + (alternatively, you can click "Run")

- if you don't have highlighted code
   + hit **command/ctrl + enter**
   + R will **run the line of code** where your cursor is at (your cursor can be anywhere in the line)
   + R will also automatically move the cursor to the next line of code
   + This is a really handy way to run code line by line

## Exercise: basic math operations
To do $\sqrt{100}$ and $e^2$:
```{webr-r}
sqrt(100)
exp(2)
```

To do $\ln{(1000)}$ (log **base e** is the default; can change the base using `log(1000, base=10)`)
```{webr-r}
log(1000)
log(1000, base=10)
```

Exercise: calculate the following in R

1. $\frac{3\times 2 + 4^2}{5.5 \times 2}$
2. $\frac{e^{5.1}+23}{\frac{3}{4} \times 5}$
3. $\frac{\sqrt{12}}{\ln{(8-4.37)}}$

<details>
<summary>Show solution</summary>

```{webr-r}
# 1. (3*2 + 4^2) / (5.5 * 2)
(3*2 + 4^2) / (5.5 * 2)

# 2. (e^5.1 + 23) / ((3/4) * 5)
(exp(5.1) + 23) / ((3/4) * 5)

# 3. sqrt(12) / log(8 - 4.37)
sqrt(12) / log(8 - 4.37)
```
</details>



## Formatting basics
- Use \# to comment out text

- Space and empty lines, in general, do not matter in R

- R is case sensitive!
```{webr-r}
Sqrt(100)  # this will give you an error
```

- Use ';' to put multiple lines of code on the same line
```{webr-r}
2+4; 5*3
```

- Can separate one line of code into multiple lines, as long as it is obvious that the previous line has not ended
```{webr-r}
# works
3 + 2 - 7 *
  1000 + 10 - 100

```

```{webr-r}
# does not work
3 + 2 - 7
* 1000 + 10 - 100
```


## R packages
The ability to develop and use **R packages** is a big advantage of R over other commercial statistical software like SPSS or excel.

Before you can use a package, there are two steps:

(1) download and **install** the package: you only need to do this once per computer
    + How: click install under packages (recommended)
    + OR run `install.packages()`
(2) **load** the package: you need to do this each time you start a new R session
    + How: check the box under packages 
    + OR run `library()` (recommended)

```{webr-r}
#install.packages('Lock5Data')
library('Lock5Data')
#install.packages('tidyverse')
library('tidyverse')
```


- The **Lock5Data** package contains dataset from Lock, 
Lock, Lock, Lock, and Lock textbook [*Statistics: Unlocking the Power of
Data*](http://www.lock5stat.com/datapage3e.html)

- The [**tidyverse**](https://www.tidyverse.org/packages/) is a collection of very popular and powerful packages for data manipulation, visualization, formatting, etc.


## Cereal dataset

We will explore the Cereal dataset to get more familiar with R.  The code will be explained in more detail later.

1. Create a **health score** of cereals with your own formula, and store it in the dataset as `health`.

2. Print out the names of the cereals from the dataset.

3. Print out information of cereals that are manufactured by Kellog.

4. Print out information of cereals with a fiber content greater than 3 (grams per cup).

5. Print out information of the top 5 healthy cereals according to the score `health`.

6. Generate a scatterplot between `Calories` and `health`.  Briefly discuss any findings (does your health score make sense based on the calories?)


<details>
<summary>Show sample code</summary>

```{webr-r}
# 1. Create a health score
Cereal$health <- Cereal$Fiber - Cereal$Sugar

# equivalent tidyverse version
Cereal <- Cereal %>% mutate(health = Fiber - Sugar)

# 2. Print out the names of the cereals
Cereal$Name
Cereal %>% select(Name)

# 3. Print out information of cereals manufactured by Kellog
Cereal[Cereal$Manufacturer == "Kellog", ]
Cereal %>% 
  filter(Manufacturer == 'Kellog')

# 4. Print out information of cereals with a fiber content greater than 3
Cereal[Cereal$Fiber > 3, ]
Cereal %>% filter(Fiber > 3)

# 5. Print out information of the top 5 healthy cereals
Cereal %>% 
  arrange(desc(health)) %>%
  slice(1:5) %>%
  select(Name, health)

# 6. Generate a scatterplot between Calories and health
plot(Cereal$Calories, Cereal$health,
     pch=16, col='salmon',
     xlab='Calories', ylab='Health score')
```

</details>



# R objects; numbers and vectors

## Creating an R object
- Examples of R object: a number, a vector, a data frame, a function, etc.

- To **assign** a number to an R object called "a":
```{webr-r}
a=34
a = 34
a<-34
a <- 34
```
- These lines of code are equivalent - personal habit
- <u>Very useful</u>: you can print out an R object simply by running it
  + try: highlight "a" and run it


## Vector: a collection of values
- Example: `Cereal$Name` is a vector of 30 values

Recall: R is case sensitive!
```{webr-r}
# these will give you errors
Plot(cereal$Carbs, cereal$Calories)
```
```{webr-r}
plot(cereal$Carbs, cereal$Calories)
```
```{webr-r}
plot(Cereal$carbs, Cereal$Calories)
```

- You will see these errors pretty often:
    + **Object `Cereal' not found**: check spelling; check where you thought you have created this object (did you actually create it by running the code?)
    + **Could not find function `Plot'**: check spelling; check if you have loaded relevant package
    + **'x' and 'y' lengths differ**: separately print out x and y to check


- When creating a vector, use `c( , )` for combined (concatenated) values
```{webr-r}
c(1,2,3)
c(Cereal$Name, "Puffins")
```

## Vector arithmetic
- When you apply an operation to a vector, R will perform the operation to *each element* in the vector 

```{webr-r}
2000 - Cereal$Calories
```

- Important note: the vector **Cereal$Calories** is not changed and the new values are not stored (verify this); if you want to store the new vector, you need to assign it to a new R object or override an existing R object
  
```{webr-r}
remainCalories <- 2000 - Cereal$Calories
```

- When you do something like `vector1 ± vector2`, R will do the arithmetic operation *element by element*
  + if they have different lengths, R will give you a **warning** (and recycle the shorter vector)
  

```{webr-r}
c(1,2,3) + c(1,1,1)
c(1,2,3) + c(1,1)
Cereal$Protein - Cereal$Calories/100
```  


- R has built-in *functions* for common operations on vectors:
```{webr-r}
mean(Cereal$Calories)
sum(Cereal$Calories)/length(Cereal$Calories)
range(Cereal$Calories)
min(Cereal$Calories)
sd(Cereal$Calories)
summary(Cereal$Calories)
```



## Character strings
- Put characters in double or single quotes
- R knows certain characters, like `col = "red"`
```{webr-r}
mycol <- "red"  #stores 'red' in an R object mycol
mycols <- c('red','green','blue') #recall how to do vectors
```

```{webr-r}
# does not work
mycol <- red
```

## Logicals
- **TRUE** (or T) and **FALSE** (or F) are special logical characters when NOT in quotation

- **Numerically, R treats TRUE as 1 and FALSE as 0**

- **A variable with only two options**, (e.g., yes/no, true/false), is referred to as a "binary," "dichotomous," "indicator," or "dummy" variable
    - Example: University type (public/private); it is customary to name it `public` and code it as `TRUE` (1) for public and `FALSE` (0) for private

- Exercise: create a vector, `names`, that contains the names of some students; create another vector, `cats`, that indicates if a student owns at least one cat or not

<details>
<summary>Show sample code</summary>

```{webr-r}
names <- c("Tom","Mary","Kate","James")
cats <- c(T,T,T,F)
as.numeric(cats)
```
</details>

- Q: what will **mean(cats)** return?
<details>
<summary>Show answer</summary>
The mean function will return the proportion of TRUE values in the logical vector (or, in general, 1-coded values for 0/1 variables). In this case, it will return the proportion of students who own at least one cat (i.e., 3/4 using the above sample code).
</details>


- Logical vectors are very useful for *subsetting* dataset.  For example, to get all the names of students who own cats:
```{webr-r}
names[cats]
```


- Logical vectors can be created using **logical operations**: $<, <=, >, >=, ==, !=$
```{webr-r}
Cereal$Calories < 100
Cereal$Company == 'K'
```

- **IMPORTANT: do not confuse `==` and `=`!**

- **which( )** will return the INDEX of TRUE values
```{webr-r}
which(Cereal$Calories < 100)
which(Cereal$Company=='K')
```


# Vector modification and subsetting

## Append to a vector
- The easiest way to append to an existing vector is to use `c( , )`
```{webr-r}
# To append elements to a vector
myfavs <- c("Puffins","Reese's Puffs")
c(Cereal$Name, myfavs)
```

- The function **append** is more general. Run **?append** to get more information

- Nothing is stored!  Recall, to store, you have to assign the new vector to an R object
```{webr-r}
allCereal <- c(Cereal$Name, myfavs)
allCereal
```


## Subset
Subsetting is the process of extracting element(s) from a vector or a dataset.  The basic idea is to specify the position(s) of the elements you want, using square brackets `[]`.

```{webr-r}
names

#To get the 2nd person's name
names[2]

#To get the 2nd and 3rd persons' names
#name[2,3] does not work! Always use c( , ) for vectors!
names[c(2,3)]
```

Q: what will **names[c(2,2,2,3)]** return?
```{webr-r}
names[c(2,2,2,3)]
```


Can also subset using a logic condition: **R returns elements corresponding to TRUE**
```{webr-r}
names[cats]
```


- Alternatively, you can use the `which( )` function to tell you the index position first
```{webr-r}
Cereal$Name[Cereal$Protein>3]
which(Cereal$Protein>3)
Cereal$Name[which(Cereal$Protein>3)]
```



## Delete from a vector

Use the **minus sign** to delete the corresponding elements from a vector
```{webr-r}
names[-2]
names[-c(2,3)]
```

Note: **tidyverse** has functions to do data modification and subsetting in a more readable way (e.g., `filter()`, `select()`, `mutate()`, `arrange()`). More on this later.

## Useful functions for creating vectors
```{webr-r}
c(1:5)

# seq( ) is more general
seq(from=2,to=8,by=2)
seq(from=0,to=1,length.out=5)

rep(2,6)
```

```{webr-r}
#Useful for indexing
Cereal$Name[c(1:5)]
Cereal$Name[1:5]
```



